image: docker:latest
stages:
  - build
  - test

services:
  - mysql:5
  
variables:
  MYSQL_ROOT_PASSWORD: mysqlpassword
  MYSQL_USER: "guestbook"
  MYSQL_PASSWORD: "guestbook_pass"
  MYSQL_DATABASE: "guestbook"

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

guestbook_image_build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/fufuhu/hands_on_sample/guestbook:latest .
    - docker push registry.gitlab.com/fufuhu/hands_on_sample/guestbook:latest
  tags:
    - docker

guestbook_test:
  stage: test
  script:
    - |
      echo "Before running test. Wait 10 sec."
      sleep 10
      docker run --rm registry.gitlab.com/fufuhu/hands_on_sample/guestbook:latest 'python manage.py test --settings sampleapp.settings_prod'

