mysql:
    image: "mysql:5"
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: mysqlpassword
        MYSQL_USER: "guestbook"
        MYSQL_PASSWORD: "guestbook_pass"
        MYSQL_DATABASE: "guestbook"
    ports:
        - "3306:3306"